### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by placentiusz** [prodipta/techchart#1]
devtools::install_github("prodipta/techchar")
Downloading GitHub repo prodipta/techchar@master
from URL https://api.github.com/repos/prodipta/techchar/zipball/master
Installation failed: Not Found (404)

From RStudioi 1.1.442

**Comment by prodipta** [comment]
try the correct name please (ending t missing)

**Comment by placentiusz** [comment]
The error is in README.md  file.
install.packages ("devtools")
devtools :: install_github ("prodipta / techchar")
this includes some codes in C ++, and hence will require RTools (windows) or Xcode (Mac) and compilers / libraries for building from source

**Comment by prodipta** [comment]
thanks for pointing out, now fixed
