### ISSUE TITLE
Compile error - mac osx

### ISSUE THREAD

**Issue by placentiusz** [prodipta/techchart#2]
In file  techchart/src/findlines.cpp  the abs function is defined, which conflicts with the abs function in math.h during complications(compilation error). 
After changing the name of the abs function to techchart_abs in findlines.cpp and changes in the .R files, everything is compiled and running. 

OS: Mac OSX,  clang++ compiler from xcode

**Comment by prodipta** [comment]
Thanks for reporting this. It is a known issue with clang, which defines abs with an exception specifier. Replacing the name of the function in the techchart package (or probably upgrading to C++ 11 compliant compiler where the exception specifier is probably deprecated [not-tested]) should work.
