### ISSUE TITLE
installing techchart on Windows VM

### ISSUE THREAD

**Issue by jguevara0629** [prodipta/techchart#3]
Hello, I have installed techchart on standard Windows computers successfully but i am havnig issues installing on a Windows VM. Maybe I am overlooking something.... I installing the latest version on RTools without a problem. When I run the following code I receive an error:

install.packages("remotes",repos="http://cran.us.r-project.org");library("remotes")
install_github("prodipta/techchart");library("techchart")

install.packages("remotes",repos="http://cran.us.r-project.org");library("remotes")
Installing package into ‘\\vmware-host/Shared Folders/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
trying URL 'http://cran.us.r-project.org/bin/windows/contrib/3.5/remotes_1.1.1.zip'
Content type 'application/zip' length 138057 bytes (134 KB)
downloaded 134 KB

package ‘remotes’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\Jguevara\AppData\Local\Temp\RtmpsBfreU\downloaded_packages
> install_github("prodipta/techchart");library("techchart")
Downloading GitHub repo prodipta/techchart@master
Installing package into ‘\\vmware-host/Shared Folders/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
* installing *source* package 'techchart' ...
** libs

*** arch - i386
C:/Rtools/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG  -I"\\vmware-host/Shared Folders/Documents/R/win-library/3.5/Rcpp/include"        -O2 -Wall  -mtune=generic -c RcppExports.cpp -o RcppExports.o
RcppExports.cpp:4:18: fatal error: Rcpp.h: No such file or directory
 #include <Rcpp.h>
                  ^
compilation terminated.
make: *** [C:/PROGRA~1/R/R-35~1.1/etc/i386/Makeconf:215: RcppExports.o] Error 1
ERROR: compilation failed for package 'techchart'
* removing '\\vmware-host/Shared Folders/Documents/R/win-library/3.5/techchart'
In R CMD INSTALL
Warning message:
In i.p(...) :
  installation of package ‘C:/Users/Jguevara/AppData/Local/Temp/RtmpsBfreU/remotes21a85dff27d4/prodipta-techchart-52732be’ had non-zero exit status
Error in library("techchart") : there is no package called ‘techchart’

If I understand correctly, it is having issues finding at : "\\vmware-host/Shared Folders/Documents/R/win-library/3.5/Rcpp/include"  ? When I check that file path the header file is there

**Comment by prodipta** [comment]
I have never tried this compilation on vmware, but I think this is a problem with Rcpp. This [link](https://stackoverflow.com/questions/37839042/cannot-compile-from-source-with-rcpp-on-windows-7) may give some hints. If this fixes the issue (or does not) let me know.

**Comment by prodipta** [comment]
Also it is generally [advised](https://cran.r-project.org/bin/windows/base/rw-FAQ.html) not have spaces in path name for R installation. Your "Shared Folder" may create problems

**Comment by jguevara0629** [comment]
@prodipta No luck on Windows VM but it worked on Linux VM, so the VM is not the issue, For some reason it cannot find the Rcpp header but I even looked in the DESCRIPTION file but everything necessary was there. Tried installing dependencies first and then techcharts as well with no avail.

**Comment by prodipta** [comment]
thanks for the update. I am closing this, as it appears it is not an issue with this package itself.
